In [ ]:
%%cmd
pip install watermark

In [2]:
%load_ext watermark

In [39]:
%watermark -a 'Chiang' -d -v -m -p numpy,pandas,matplotlib,scipy,sklearn

Chiang 2020-09-17 

CPython 3.7.4
IPython 7.8.0

numpy 1.19.2
pandas 0.25.1
matplotlib 3.3.2
scipy 1.5.2
sklearn 0.23.2

compiler   : MSC v.1915 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
CPU cores  : 16
interpreter: 64bit


In [10]:
import numpy  as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()
X, y = digits.data, digits.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=250)

In [6]:
X_train.shape

(1257, 64)

In [8]:
X_test.shape

(540, 64)

In [12]:
y_train.shape

(1257,)

In [14]:
y_train

array([0, 3, 4, ..., 1, 1, 9])

In [16]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
X_train[0]

array([ 0.,  0.,  0., 12.,  6.,  0.,  0.,  0.,  0.,  0.,  8., 15., 13.,
        4.,  0.,  0.,  0.,  5., 16.,  6.,  3., 12.,  0.,  0.,  0.,  7.,
       14.,  1.,  0., 11.,  5.,  0.,  0.,  3., 14.,  0.,  0.,  7., 10.,
        0.,  0.,  1., 14.,  2.,  0.,  9.,  9.,  0.,  0.,  0.,  9., 11.,
        6., 15.,  5.,  0.,  0.,  0.,  0., 10., 16., 11.,  0.,  0.])

In [20]:
#建模，探索建模结果

gnb = GaussianNB().fit(X_train, y_train)
acc_score = gnb.score(X_test, y_test)

In [22]:
acc_score

0.825925925925926

In [24]:
y_pred = gnb.predict(X_test)

In [26]:
y_pred

array([7, 2, 1, 4, 7, 2, 0, 4, 2, 7, 7, 5, 4, 1, 0, 1, 3, 5, 4, 4, 8, 8,
       5, 7, 7, 1, 3, 9, 7, 7, 1, 4, 7, 8, 1, 6, 1, 8, 1, 8, 7, 9, 6, 0,
       7, 8, 2, 8, 0, 0, 8, 1, 7, 5, 1, 4, 0, 7, 5, 3, 3, 4, 2, 8, 7, 6,
       0, 8, 6, 3, 5, 1, 1, 7, 1, 1, 3, 4, 1, 2, 8, 5, 9, 7, 8, 4, 3, 0,
       8, 6, 8, 9, 0, 7, 1, 8, 7, 5, 4, 1, 7, 4, 0, 5, 1, 4, 5, 8, 9, 2,
       1, 4, 8, 2, 7, 2, 3, 1, 0, 0, 1, 6, 8, 7, 3, 5, 3, 2, 5, 1, 1, 6,
       6, 3, 7, 7, 1, 2, 7, 2, 8, 9, 2, 0, 2, 8, 0, 0, 9, 2, 0, 7, 6, 7,
       8, 1, 6, 4, 5, 1, 3, 6, 3, 9, 5, 6, 2, 9, 3, 6, 5, 4, 2, 2, 0, 4,
       7, 1, 1, 6, 7, 2, 7, 7, 5, 9, 5, 5, 4, 3, 6, 1, 2, 8, 7, 2, 0, 1,
       1, 5, 6, 3, 4, 4, 1, 1, 6, 7, 3, 5, 6, 1, 1, 3, 8, 1, 1, 8, 8, 0,
       7, 0, 4, 7, 2, 6, 8, 0, 4, 0, 1, 1, 4, 1, 8, 5, 5, 6, 9, 9, 1, 9,
       8, 1, 0, 3, 3, 1, 2, 1, 4, 7, 8, 8, 3, 5, 5, 9, 2, 7, 5, 9, 3, 2,
       2, 8, 7, 8, 1, 7, 1, 1, 1, 0, 0, 0, 3, 0, 0, 6, 6, 7, 6, 9, 3, 9,
       7, 0, 9, 7, 8, 9, 6, 6, 5, 8, 2, 6, 7, 1, 4,

In [28]:
prob = gnb.predict_proba(X_test)

In [30]:
prob.shape

(540, 10)

In [32]:
prob

array([[0.00000000e+000, 0.00000000e+000, 5.36939156e-036, ...,
        1.00000000e+000, 5.03552651e-026, 8.76995854e-051],
       [0.00000000e+000, 0.00000000e+000, 9.99999994e-001, ...,
        0.00000000e+000, 3.20241145e-025, 1.38116154e-075],
       [0.00000000e+000, 1.00000000e+000, 6.70634375e-024, ...,
        1.07748896e-148, 1.35724237e-013, 5.96201065e-050],
       ...,
       [0.00000000e+000, 1.00000000e+000, 5.98777614e-035, ...,
        0.00000000e+000, 6.13351362e-016, 3.60244570e-026],
       [0.00000000e+000, 0.00000000e+000, 2.66211598e-121, ...,
        2.97279195e-016, 1.58526722e-046, 2.83896605e-028],
       [0.00000000e+000, 0.00000000e+000, 7.32535139e-109, ...,
        9.99999963e-001, 3.68321399e-008, 3.23272603e-094]])

In [34]:
prob[1,:].sum()

1.0000000000000004

In [36]:
prob.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [37]:
# 使用混淆矩阵来查看贝叶斯的分类结果
from sklearn.metrics import confusion_matrix  as CM

CM(y_test, y_pred)

array([[48,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 0, 56,  0,  0,  0,  0,  0,  1,  2,  1],
       [ 0,  4, 45,  0,  1,  0,  1,  0,  6,  0],
       [ 0,  2,  0, 41,  0,  2,  0,  6,  6,  0],
       [ 0,  6,  0,  0, 46,  1,  2, 12,  0,  0],
       [ 0,  1,  0,  0,  0, 50,  0,  2,  1,  0],
       [ 0,  0,  0,  0,  0,  0, 44,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 47,  0,  0],
       [ 0, 15,  0,  0,  0,  2,  0,  2, 37,  0],
       [ 0,  3,  1,  4,  0,  0,  1,  4,  4, 32]], dtype=int64)