In [2]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.preprocessing import MinMaxScaler

# 数据预处理 Preprocessing&Impute

## 数据无量纲化

### 数据归一化：MinMaxScaler

In [4]:
data = [[-1,2], [-0.5,6],[0,10], [1,18]]

In [5]:
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [6]:
# 实现归一化
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)

In [8]:
scaler

MinMaxScaler()

In [9]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [10]:
result_ = scaler.fit_transform(data)
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [11]:
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [12]:
# 使用MinMaxScaler的参数feature_range实现将数据归一化到[0,1]以外的范围中
data = [[-1,2], [-0.5,6],[0,10], [1,18]]
scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [14]:
MinMaxScaler?

In [15]:
# 当X中的特征数量非常多的时候，fit会报错并表示，数据量太大计算不了
# 此时使用partial_fit作为训练接口
# scaler = scaler.partial_fit(data)

In [17]:
# 使用numpy来实现归一化
X = np.array([[-1,2], [-0.5,6],[0,10], [1,18]])
# 归一化
X_nor = (X-X.min(axis=0))/(X.max(axis=0)-X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [18]:
# 逆转归一化
X_returned = X_nor * (X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)
X_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

### 数据标准化：StandardScaler

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
data = [[-1,2], [-0.5,6],[0,10], [1,18]]
scaler = StandardScaler()
scaler = scaler.fit(data)

In [21]:
scaler

StandardScaler()

In [22]:
scaler.mean_

array([-0.125,  9.   ])

In [23]:
scaler.var_

array([ 0.546875, 35.      ])

In [24]:
x_std = scaler.transform(data)

In [25]:
x_std

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [26]:
x_std.mean(), x_std.std()

(0.0, 1.0)

In [28]:
scaler.fit_transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [29]:
scaler.inverse_transform(x_std)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

## 缺失值

In [31]:
data = pd.read_csv('./Narrativedata.csv')
data.head()                   

Unnamed: 0   Age     Sex Embarked Survived
0           0  22.0    male        S       No
1           1  38.0  female        C      Yes
2           2  26.0  female        S      Yes
3           3  35.0  female        S      Yes
4           4  35.0    male        S       No

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
Unnamed: 0    891 non-null int64
Age           714 non-null float64
Sex           891 non-null object
Embarked      889 non-null object
Survived      891 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 34.9+ KB


In [35]:
# 填补年龄

Age = data.loc[:, 'Age'].values.reshape(-1,1)  # sklearn当中特征矩阵必须使二维
Age[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [nan],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [nan],
       [31.],
       [nan]])

In [36]:
from sklearn.impute import SimpleImputer

imp_mean = SimpleImputer()  # 实例化，默认均值填补
imp_median = SimpleImputer(strategy='median') #  用中位数填补
imp_0 = SimpleImputer(strategy='constant', fill_value=0)  # 用0填补

imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

imp_mean[:20], imp_median[:20], imp_0[:20]

(array([[22.        ],
        [38.        ],
        [26.        ],
        [35.        ],
        [35.        ],
        [29.69911765],
        [54.        ],
        [ 2.        ],
        [27.        ],
        [14.        ],
        [ 4.        ],
        [58.        ],
        [20.        ],
        [39.        ],
        [14.        ],
        [55.        ],
        [ 2.        ],
        [29.69911765],
        [31.        ],
        [29.69911765]]), array([[22.],
        [38.],
        [26.],
        [35.],
        [35.],
        [28.],
        [54.],
        [ 2.],
        [27.],
        [14.],
        [ 4.],
        [58.],
        [20.],
        [39.],
        [14.],
        [55.],
        [ 2.],
        [28.],
        [31.],
        [28.]]), array([[22.],
        [38.],
        [26.],
        [35.],
        [35.],
        [ 0.],
        [54.],
        [ 2.],
        [27.],
        [14.],
        [ 4.],
        [58.],
        [20.],
        [39.],
        [14.],
        [55.]

In [38]:
# 在这里用中位数填补Age

data.loc[:,'Age'] = imp_median

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
Unnamed: 0    891 non-null int64
Age           891 non-null float64
Sex           891 non-null object
Embarked      889 non-null object
Survived      891 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 34.9+ KB


In [39]:
# 使用众数填补Embarked

Embarked = data.loc[:, 'Embarked'].values.reshape(-1,1)

imp_mode = SimpleImputer(strategy='most_frequent')
data.loc[:,'Embarked'] = imp_mode.fit_transform(Embarked)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
Unnamed: 0    891 non-null int64
Age           891 non-null float64
Sex           891 non-null object
Embarked      891 non-null object
Survived      891 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 34.9+ KB


### 使用pands和numpy进行填补

In [40]:
data = pd.read_csv('./Narrativedata.csv')

data.loc[:,'Age'] = data.loc[:,'Age'].fillna(data.loc[:,'Age'].median())
data.dropna(axis=0, inplace=True)

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 5 columns):
Unnamed: 0    889 non-null int64
Age           889 non-null float64
Sex           889 non-null object
Embarked      889 non-null object
Survived      889 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 41.7+ KB


## 处理分类型特征：编码与哑变量

### LabelEncoder 标签专用，能够将分类转化为分类数值

In [42]:
from sklearn.preprocessing import LabelEncoder

y = data.iloc[:, -1]

In [43]:
y

0           No
1          Yes
2          Yes
3          Yes
4           No
        ...   
886         No
887        Yes
888         No
889    Unknown
890         No
Name: Survived, Length: 889, dtype: object

In [44]:
np.unique(y)

array(['No', 'Unknown', 'Yes'], dtype=object)

In [45]:
le = LabelEncoder()
le = le.fit(y)
label = le.transform(y)

In [46]:
le.classes_

array(['No', 'Unknown', 'Yes'], dtype=object)

In [47]:
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2,
       0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 0,
       0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2,

In [48]:
le.fit_transform(y)

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2,
       0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 0,
       0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2,

In [50]:
le.inverse_transform(label)

array(['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'Unknown', 'Yes', 'No', 'No', 'No', 'Unknown', 'No', 'Yes', 'No',
       'Yes', 'Unknown', 'Yes', 'Yes', 'Yes', 'No', 'Unknown', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Unknown', 'Yes', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'Unknown', 'No', 'Unknown',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Unknown', 'Yes',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'Unknown', 'No', 'No', 'Yes', 'No', 'No', 'Ye

In [51]:
data.iloc[:,-1] = label
data.head()

Unnamed: 0   Age     Sex Embarked  Survived
0           0  22.0    male        S         0
1           1  38.0  female        C         2
2           2  26.0  female        S         2
3           3  35.0  female        S         2
4           4  35.0    male        S         0

### OrdinalEncoder 特征专用，能够将分类特征转化为分类数值

In [52]:
from sklearn.preprocessing import OrdinalEncoder

data_ = data.copy()
data_.head()

Unnamed: 0   Age     Sex Embarked  Survived
0           0  22.0    male        S         0
1           1  38.0  female        C         2
2           2  26.0  female        S         2
3           3  35.0  female        S         2
4           4  35.0    male        S         0

In [61]:
OrdinalEncoder().fit(data_.iloc[:, 1:-1]).categories_

[array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
        26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
        39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
        52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
        65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
        78., 79., 80., 81., 82., 83., 84., 85., 86., 87.]),
 array([0., 1.]),
 array([0., 1., 2.])]

In [58]:
data_.iloc[:, 1:-1]

Age  Sex  Embarked
0    28.0  1.0       2.0
1    51.0  0.0       0.0
2    34.0  0.0       2.0
3    47.0  0.0       2.0
4    47.0  1.0       2.0
..    ...  ...       ...
886  35.0  1.0       2.0
887  24.0  0.0       2.0
888  36.0  0.0       2.0
889  34.0  1.0       0.0
890  42.0  1.0       1.0

[889 rows x 3 columns]

In [63]:
data_.iloc[:, 1:-1] = OrdinalEncoder().fit_transform(data_.iloc[:, 1:-1])
data_.head()

Unnamed: 0   Age  Sex  Embarked  Survived
0           0  28.0  1.0       2.0         0
1           1  51.0  0.0       0.0         2
2           2  34.0  0.0       2.0         2
3           3  47.0  0.0       2.0         2
4           4  47.0  1.0       2.0         0

### OneHotEncoder：独热编码，创建哑变量

In [64]:
data.head()

Unnamed: 0   Age     Sex Embarked  Survived
0           0  22.0    male        S         0
1           1  38.0  female        C         2
2           2  26.0  female        S         2
3           3  35.0  female        S         2
4           4  35.0    male        S         0

In [76]:
from sklearn.preprocessing import OneHotEncoder

X = data.iloc[:, 2:-1]

In [77]:
X

Sex Embarked
0      male        S
1    female        C
2    female        S
3    female        S
4      male        S
..      ...      ...
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

[889 rows x 2 columns]

In [78]:
enc = OneHotEncoder(categories='auto').fit(X)

In [79]:
result = enc.transform(X).toarray()

In [80]:
OneHotEncoder(categories='auto').fit_transform(X).toarray()

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [81]:
enc.get_feature_names()

array(['x0_female', 'x0_male', 'x1_C', 'x1_Q', 'x1_S'], dtype=object)

In [82]:
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [83]:
result.shape

(889, 5)

In [84]:
newdata = pd.concat([data, pd.DataFrame(result)],axis=1)

In [85]:
newdata.head()

Unnamed: 0   Age     Sex Embarked  Survived    0    1    2    3    4
0         0.0  22.0    male        S       0.0  0.0  1.0  0.0  0.0  1.0
1         1.0  38.0  female        C       2.0  1.0  0.0  1.0  0.0  0.0
2         2.0  26.0  female        S       2.0  1.0  0.0  0.0  0.0  1.0
3         3.0  35.0  female        S       2.0  1.0  0.0  0.0  0.0  1.0
4         4.0  35.0    male        S       0.0  0.0  1.0  0.0  0.0  1.0

In [86]:
newdata.drop(['Sex','Embarked'],axis=1, inplace=True)

In [87]:
newdata

Unnamed: 0   Age  Survived    0    1    2    3    4
0           0.0  22.0       0.0  0.0  1.0  0.0  0.0  1.0
1           1.0  38.0       2.0  1.0  0.0  1.0  0.0  0.0
2           2.0  26.0       2.0  1.0  0.0  0.0  0.0  1.0
3           3.0  35.0       2.0  1.0  0.0  0.0  0.0  1.0
4           4.0  35.0       0.0  0.0  1.0  0.0  0.0  1.0
..          ...   ...       ...  ...  ...  ...  ...  ...
886       886.0  27.0       0.0  1.0  0.0  0.0  0.0  1.0
887       887.0  19.0       2.0  0.0  1.0  1.0  0.0  0.0
888       888.0  28.0       0.0  0.0  1.0  0.0  1.0  0.0
889       889.0  26.0       1.0  NaN  NaN  NaN  NaN  NaN
890       890.0  32.0       0.0  NaN  NaN  NaN  NaN  NaN

[891 rows x 8 columns]

In [89]:
newdata.columns = ['order','Age', 'Survived', 'Female', 'Male', 'Embarked_C', 'Embarked_Q', 'Embarked_S']
newdata.head()

order   Age  Survived  Female  Male  Embarked_C  Embarked_Q  Embarked_S
0    0.0  22.0       0.0     0.0   1.0         0.0         0.0         1.0
1    1.0  38.0       2.0     1.0   0.0         1.0         0.0         0.0
2    2.0  26.0       2.0     1.0   0.0         0.0         0.0         1.0
3    3.0  35.0       2.0     1.0   0.0         0.0         0.0         1.0
4    4.0  35.0       0.0     0.0   1.0         0.0         0.0         1.0

## 处理连续型特征：二值化与分段

### Binarizer

In [91]:
data_2 = data.copy()
data_2.head()

Unnamed: 0   Age     Sex Embarked  Survived
0           0  22.0    male        S         0
1           1  38.0  female        C         2
2           2  26.0  female        S         2
3           3  35.0  female        S         2
4           4  35.0    male        S         0

In [92]:

from sklearn.preprocessing import Binarizer
X = data_2.iloc[:, 1].values.reshape(-1, 1)

In [94]:
transformer = Binarizer(threshold=30).fit_transform(X)

transformer

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],

### KBinsDiscretizer

In [95]:
from sklearn.preprocessing import KBinsDiscretizer

X = data.iloc[:,1].values.reshape(-1,1)
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
est.fit_transform(X)

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],

In [96]:
set(est.fit_transform(X).ravel())

{0.0, 1.0, 2.0}

In [97]:
est = KBinsDiscretizer(n_bins=3, encode='onehot', strategy='uniform')
est.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

# 特征选择 feature_selection

In [98]:
data = pd.read_csv('./digit recognizor.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [99]:
X = data.iloc[:, 1:]
y = data.iloc[:,0]

In [101]:
data

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [102]:
X.shape

(42000, 784)

In [103]:
y.shape

(42000,)

## Filter过滤法

### 方差过滤

####  VarianceThreshold

In [104]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold()  # 实例化， 不填参数默认方差为0
X_var0 = selector.fit_transform(X)

X_var0.shape

(42000, 708)

In [107]:
np.median(X.var().values)

1352.286703180131

In [108]:
x_fsvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)

In [109]:
x_fsvar.shape

(42000, 392)

In [110]:
#若特征是伯努利随机变量，假设p=0.8，即二分类特征中某种分类占到80%以上的时候删除特征
X_bvar = VarianceThreshold(.8 * (1 - .8)).fit_transform(X)
X_bvar.shape

(42000, 685)

####  方差过滤对模型的影响

In [113]:
# 1.导入模块并准备数据

from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import cross_val_score

import numpy as np

X = data.iloc[:, 1:]
y = data.iloc[:,0]

x_fsvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)

In [114]:
# 2. KNN方差过滤前

cross_val_score(KNN(), X, y).mean()

0.965857142857143

In [ ]:
# 3.KNN方差过滤后
cross_val_score(KNN(), x_fsvar, y).mean()

In [ ]:
# 4. 随机森林方差过滤前
cross_val_score(RFC(n_estimators=10, random_state=0),X, y, cv=5).mean()

In [ ]:
# 5. 随机森林方差过滤后
cross_val_score(RFC(n_estimators=10, random_state=0),x_fsvar, y, cv=5).mean()

####  选取超参数threshold

###  相关性过滤

#### 卡方过滤